/* Generated by tools/gen_opening_book.py — do not edit. */
#include "opening_book.h"

typedef struct {
  uint64_t key;
  uint8_t count;
  uint8_t from[OPENING_BOOK_MAX_ALT];
  uint8_t to[OPENING_BOOK_MAX_ALT];
  uint8_t weight[OPENING_BOOK_MAX_ALT];
} opening_book_entry_t;

static const opening_book_entry_t s_book[] = {
  { 0x0023B8E62F5D7089u, 4u, {52,50,50,52}, {36,34,42,44}, {100,80,70,70} },
  { 0x034E044383B85425u, 1u, {51,0,0,0}, {35,0,0,0}, {70,0,0,0} },
  { 0x035C3ED1A9AA30F9u, 1u, {51,0,0,0}, {35,0,0,0}, {80,0,0,0} },
  { 0x03622172DFE983CDu, 4u, {12,6,10,11}, {28,21,26,27}, {100,80,80,80} },
  { 0x0875F3157296353Au, 1u, {21,0,0,0}, {27,0,0,0}, {60,0,0,0} },
  { 0x0EA51FD25B9C251Fu, 1u, {52,0,0,0}, {44,0,0,0}, {70,0,0,0} },
  { 0x1DAA4452420F06FDu, 2u, {6,1,0,0}, {21,18,0,0}, {80,70,0,0} },
  { 0x1EE3697EF73F5C7Fu, 1u, {52,0,0,0}, {44,0,0,0}, {70,0,0,0} },
  { 0x275265FBC4EB3E83u, 1u, {62,0,0,0}, {45,0,0,0}, {60,0,0,0} },
  { 0x289B8B423461DEF5u, 1u, {1,0,0,0}, {18,0,0,0}, {80,0,0,0} },
  { 0x2E0F494B333C348Bu, 1u, {62,0,0,0}, {45,0,0,0}, {70,0,0,0} },
  { 0x2E45F7A9BB001825u, 1u, {6,0,0,0}, {21,0,0,0}, {60,0,0,0} },
  { 0x2F864347761959A5u, 1u, {6,0,0,0}, {21,0,0,0}, {80,0,0,0} },
  { 0x3111A2A861045A6Bu, 2u, {51,62,0,0}, {35,45,0,0}, {80,70,0,0} },
  { 0x33078AB672198E88u, 1u, {42,0,0,0}, {35,0,0,0}, {70,0,0,0} },
  { 0x37948AA1ADA0C7FBu, 3u, {5,5,11,0}, {26,33,27,0}, {100,100,80,0} },
  { 0x3E19DF94C61A0443u, 1u, {10,0,0,0}, {26,0,0,0}, {70,0,0,0} },
  { 0x41A96266657C1313u, 2u, {57,62,0,0}, {42,45,0,0}, {100,80,0,0} },
  { 0x4405AA9C98758E91u, 1u, {52,0,0,0}, {44,0,0,0}, {80,0,0,0} },
  { 0x45FCF4882FAB9D93u, 1u, {62,0,0,0}, {45,0,0,0}, {80,0,0,0} },
  { 0x4645CB1EBE50DB1Au, 1u, {21,0,0,0}, {27,0,0,0}, {80,0,0,0} },
  { 0x47050470FDDD14BDu, 2u, {51,62,0,0}, {35,45,0,0}, {80,80,0,0} },
  { 0x573891C43460C467u, 1u, {62,0,0,0}, {45,0,0,0}, {70,0,0,0} },
  { 0x574913EF3A9790DDu, 1u, {51,0,0,0}, {35,0,0,0}, {70,0,0,0} },
  { 0x5B9C523CB004840Bu, 1u, {61,0,0,0}, {25,0,0,0}, {70,0,0,0} },
  { 0x5BD5EF3A58824673u, 2u, {51,57,0,0}, {43,42,0,0}, {80,80,0,0} },
  { 0x5FE343C7D7C7DBF5u, 1u, {1,0,0,0}, {18,0,0,0}, {70,0,0,0} },
  { 0x6B266DCA2B1AD8C3u, 1u, {12,0,0,0}, {28,0,0,0}, {80,0,0,0} },
  { 0x7F38884359FA218Bu, 1u, {1,0,0,0}, {18,0,0,0}, {70,0,0,0} },
  { 0x827306DCC62EC77Bu, 1u, {11,0,0,0}, {27,0,0,0}, {70,0,0,0} },
  { 0x82E88A13594334C5u, 1u, {6,0,0,0}, {21,0,0,0}, {100,0,0,0} },
  { 0x8540A4829B5B209Bu, 1u, {51,0,0,0}, {35,0,0,0}, {80,0,0,0} },
  { 0x87CB833F7434B7D5u, 1u, {28,0,0,0}, {35,0,0,0}, {70,0,0,0} },
  { 0x89125D8D958FDB35u, 1u, {11,0,0,0}, {27,0,0,0}, {70,0,0,0} },
  { 0x8C99444F262B2FC1u, 1u, {1,0,0,0}, {18,0,0,0}, {60,0,0,0} },
  { 0x8CF0C78E68C15AE5u, 1u, {10,0,0,0}, {26,0,0,0}, {80,0,0,0} },
  { 0x8F440EBCD8744DE5u, 1u, {51,0,0,0}, {35,0,0,0}, {70,0,0,0} },
  { 0x9082CAC922400F4Bu, 1u, {48,0,0,0}, {40,0,0,0}, {100,0,0,0} },
  { 0x90D5EE63DAEDA3C2u, 1u, {21,0,0,0}, {27,0,0,0}, {80,0,0,0} },
  { 0x91A3BCF0517061A3u, 1u, {11,0,0,0}, {27,0,0,0}, {60,0,0,0} },
  { 0x91BCCD0C949758CBu, 1u, {6,0,0,0}, {21,0,0,0}, {60,0,0,0} },
  { 0x99369934F1EACC3Bu, 1u, {6,0,0,0}, {21,0,0,0}, {60,0,0,0} },
  { 0x9E77A420D943954Du, 1u, {10,0,0,0}, {26,0,0,0}, {80,0,0,0} },
  { 0xA2F7044EAD0B069Bu, 1u, {1,0,0,0}, {18,0,0,0}, {70,0,0,0} },
  { 0xA5EF1DEA8F37FD43u, 1u, {11,0,0,0}, {27,0,0,0}, {80,0,0,0} },
  { 0xA807B1BA9C7ACD06u, 2u, {61,62,0,0}, {52,45,0,0}, {100,100,0,0} },
  { 0xAC4F3BD96B962ED3u, 1u, {51,0,0,0}, {43,0,0,0}, {60,0,0,0} },
  { 0xB0B130FE50413863u, 1u, {10,0,0,0}, {26,0,0,0}, {70,0,0,0} },
  { 0xB20A270813959219u, 1u, {51,0,0,0}, {35,0,0,0}, {80,0,0,0} },
  { 0xB24D0EA5D770524Bu, 1u, {33,0,0,0}, {24,0,0,0}, {100,0,0,0} },
  { 0xBC5D9B0CC943FD53u, 1u, {34,0,0,0}, {27,0,0,0}, {80,0,0,0} },
  { 0xBD4C1CE7EDF5BF45u, 2u, {6,1,0,0}, {21,18,0,0}, {70,60,0,0} },
  { 0xCC63EAB01040A00Du, 2u, {61,57,0,0}, {25,42,0,0}, {70,60,0,0} },
  { 0xD0878A36CC8333B3u, 1u, {34,0,0,0}, {27,0,0,0}, {60,0,0,0} },
  { 0xD146D1F07515D34Fu, 1u, {62,0,0,0}, {45,0,0,0}, {80,0,0,0} },
  { 0xD33B5497916E56F5u, 1u, {11,0,0,0}, {27,0,0,0}, {70,0,0,0} },
  { 0xD7A751A6BAD312A9u, 2u, {35,52,0,0}, {26,44,0,0}, {80,80,0,0} },
  { 0xDCC0F6C0253B3509u, 3u, {62,52,50,0}, {45,36,34,0}, {80,70,60,0} },
  { 0xE21DFCC097FA122Eu, 1u, {11,0,0,0}, {19,0,0,0}, {100,0,0,0} },
  { 0xE4F64A509F0FF8FBu, 1u, {34,0,0,0}, {27,0,0,0}, {80,0,0,0} },
  { 0xE52F9A36A343CFEBu, 1u, {11,0,0,0}, {27,0,0,0}, {80,0,0,0} },
  { 0xE5A5620CD1491B3Eu, 1u, {61,0,0,0}, {34,0,0,0}, {100,0,0,0} },
  { 0xE80E25A6022343AFu, 1u, {52,0,0,0}, {44,0,0,0}, {60,0,0,0} },
  { 0xF382E195E0596173u, 1u, {62,0,0,0}, {45,0,0,0}, {70,0,0,0} },
};

enum { OPENING_BOOK_ENTRY_COUNT = 64 };

static uint64_t fnv1a64_key(const uint8_t key[34]) {
  uint64_t h = UINT64_C(1469598103934665603);
  unsigned i;
  for (i = 0; i < 34u; i++) {
    h ^= (uint64_t)key[i];
    h *= UINT64_C(1099511628211);
  }
  return h;
}

static uint32_t book_rng_next(uint32_t *state) {
  *state = *state * 1664525u + 1013904223u;
  return *state >> 8;
}

static bool pick_weighted(const opening_book_entry_t *e, uint32_t book_seed,
                        uint8_t *from, uint8_t *to) {
  unsigned i;
  unsigned best = 0;
  if (e->count == 0) {
    return false;
  }
  if (book_seed == 0u) {
    for (i = 1; i < e->count; i++) {
      if (e->weight[i] > e->weight[best]) {
        best = i;
      }
    }
    *from = e->from[best];
    *to = e->to[best];
    return true;
  }
  {
    uint32_t rng = book_seed;
    uint32_t roll;
    uint32_t total = 0;
    for (i = 0; i < e->count; i++) {
      total += (uint32_t)e->weight[i];
    }
    if (total == 0u) {
      return false;
    }
    roll = book_rng_next(&rng) % total;
    for (i = 0; i < e->count; i++) {
      if (roll < (uint32_t)e->weight[i]) {
        *from = e->from[i];
        *to = e->to[i];
        return true;
      }
      roll -= (uint32_t)e->weight[i];
    }
    *from = e->from[e->count - 1u];
    *to = e->to[e->count - 1u];
    return true;
  }
}

static const opening_book_entry_t *find_entry(uint64_t kh) {
  size_t lo = 0;
  size_t hi = OPENING_BOOK_ENTRY_COUNT;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    if (s_book[mid].key < kh) {
      lo = mid + 1;
    } else if (s_book[mid].key > kh) {
      hi = mid;
    } else {
      return &s_book[mid];
    }
  }
  return NULL;
}

bool chess_opening_book_probe(const chess_position *pos, uint32_t book_seed,
                              bool book_enabled, chess_move *out) {
  uint8_t key[34];
  const opening_book_entry_t *e;
  uint8_t from;
  uint8_t to;
  chess_position probe;
  chess_undo undo;
  unsigned last;
  if (!book_enabled || pos == NULL || out == NULL) {
    return false;
  }
  chess_position_key(pos, key);
  e = find_entry(fnv1a64_key(key));
  if (e == NULL) {
    return false;
  }
  if (!pick_weighted(e, book_seed, &from, &to)) {
    return false;
  }
  out->from = from;
  out->to = to;
  out->promotion = CHESS_EMPTY;
  last = (pos->side_to_move == CHESS_WHITE) ? 7u : 0u;
  if (pos->board[from].type == CHESS_PAWN && to / 8u == last) {
    out->promotion = CHESS_QUEEN;
  }
  probe = *pos;
  if (chess_make(&probe, *out, &undo) != CHESS_OK) {
    return false;
  }
  return true;
}

size_t chess_opening_book_position_count(void) {
  return OPENING_BOOK_ENTRY_COUNT;
}

int chess_opening_book_selfcheck(void) {
  return 0;
}
