/* Generated by tools/gen_opening_book.py — do not edit. */
#include "opening_book.h"

typedef struct {
  uint64_t key;
  uint8_t count;
  uint8_t from[OPENING_BOOK_MAX_ALT];
  uint8_t to[OPENING_BOOK_MAX_ALT];
  uint8_t weight[OPENING_BOOK_MAX_ALT];
} opening_book_entry_t;

static const opening_book_entry_t s_book[] = {
  { 0x0023B8E62F5D7089u, 4u, {52,50,52,50}, {36,34,44,42}, {100,78,36,22} },
  { 0x034E044383B85425u, 1u, {51,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0x035C3ED1A9AA30F9u, 1u, {51,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0x03622172DFE983CDu, 4u, {12,11,6,10}, {28,27,21,26}, {100,77,25,20} },
  { 0x048AEE88D4AA7365u, 1u, {62,0,0,0}, {45,0,0,0}, {50,0,0,0} },
  { 0x04B4593806939F3Du, 1u, {51,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0x0A383DB15C38EC5Cu, 1u, {35,0,0,0}, {26,0,0,0}, {100,0,0,0} },
  { 0x0BA56E8DF59F28C3u, 1u, {11,0,0,0}, {27,0,0,0}, {100,0,0,0} },
  { 0x15B2879EE1FE8447u, 1u, {61,0,0,0}, {54,0,0,0}, {100,0,0,0} },
  { 0x19B4ACD39B06FD74u, 1u, {6,0,0,0}, {21,0,0,0}, {100,0,0,0} },
  { 0x1DAA4452420F06FDu, 3u, {14,1,6,0}, {22,18,21,0}, {100,87,87,0} },
  { 0x1FA1DF72DE583ED0u, 1u, {14,0,0,0}, {22,0,0,0}, {100,0,0,0} },
  { 0x271DF5C1E782E973u, 1u, {54,0,0,0}, {46,0,0,0}, {100,0,0,0} },
  { 0x274E898B60E97AC5u, 1u, {62,0,0,0}, {45,0,0,0}, {100,0,0,0} },
  { 0x2E0F494B333C348Bu, 1u, {52,0,0,0}, {44,0,0,0}, {100,0,0,0} },
  { 0x2F0AAD7A622D819Bu, 1u, {11,0,0,0}, {28,0,0,0}, {100,0,0,0} },
  { 0x2F864347761959A5u, 2u, {10,6,0,0}, {18,21,0,0}, {100,87,0,0} },
  { 0x3111A2A861045A6Bu, 4u, {51,62,50,52}, {35,45,34,44}, {100,94,25,22} },
  { 0x3506FB8F3BF093C4u, 1u, {48,0,0,0}, {40,0,0,0}, {100,0,0,0} },
  { 0x37948AA1ADA0C7FBu, 4u, {1,5,5,5}, {18,12,26,33}, {100,100,100,100} },
  { 0x39620D47AFD5E6D3u, 1u, {34,0,0,0}, {27,0,0,0}, {100,0,0,0} },
  { 0x3973D9A75852EBC4u, 1u, {51,0,0,0}, {43,0,0,0}, {100,0,0,0} },
  { 0x41009298487BC250u, 1u, {50,0,0,0}, {34,0,0,0}, {100,0,0,0} },
  { 0x41A96266657C1313u, 2u, {57,62,0,0}, {42,45,0,0}, {100,100,0,0} },
  { 0x4209D8E97FC69F37u, 1u, {61,0,0,0}, {54,0,0,0}, {100,0,0,0} },
  { 0x4313E6C01EC1F9A9u, 3u, {13,1,6,0}, {21,18,21,0}, {100,87,87,0} },
  { 0x43A7DEE73DE09655u, 1u, {1,0,0,0}, {11,0,0,0}, {50,0,0,0} },
  { 0x4405AA9C98758E91u, 2u, {52,54,0,0}, {44,46,0,0}, {100,100,0,0} },
  { 0x44A6F732AF02A118u, 1u, {59,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0x4645CB1EBE50DB1Au, 1u, {21,0,0,0}, {27,0,0,0}, {100,0,0,0} },
  { 0x47050470FDDD14BDu, 4u, {50,51,52,53}, {34,35,44,37}, {100,100,100,100} },
  { 0x47D89FF6DEC648ABu, 1u, {14,0,0,0}, {22,0,0,0}, {100,0,0,0} },
  { 0x573891C43460C467u, 2u, {35,62,0,0}, {28,45,0,0}, {100,87,0,0} },
  { 0x5B9C523CB004840Bu, 1u, {61,0,0,0}, {25,0,0,0}, {100,0,0,0} },
  { 0x5BD5EF3A58824673u, 2u, {51,52,0,0}, {43,44,0,0}, {100,100,0,0} },
  { 0x5FE343C7D7C7DBF5u, 1u, {1,0,0,0}, {18,0,0,0}, {100,0,0,0} },
  { 0x608E9930BA83BBCBu, 1u, {12,0,0,0}, {20,0,0,0}, {100,0,0,0} },
  { 0x70F1BC6DACDCCAA5u, 1u, {28,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0x754F85D043BF483Cu, 1u, {62,0,0,0}, {45,0,0,0}, {50,0,0,0} },
  { 0x762308E132FCECD0u, 1u, {35,0,0,0}, {28,0,0,0}, {100,0,0,0} },
  { 0x768A1FCF058CBA64u, 1u, {11,0,0,0}, {27,0,0,0}, {50,0,0,0} },
  { 0x786AC4748334B662u, 1u, {58,0,0,0}, {37,0,0,0}, {100,0,0,0} },
  { 0x7AA15B3A5B370DF5u, 1u, {42,0,0,0}, {34,0,0,0}, {100,0,0,0} },
  { 0x82E88A13594334C5u, 1u, {6,0,0,0}, {21,0,0,0}, {100,0,0,0} },
  { 0x8540A4829B5B209Bu, 1u, {49,0,0,0}, {41,0,0,0}, {100,0,0,0} },
  { 0x86E693AF8F1A5742u, 1u, {51,0,0,0}, {43,0,0,0}, {100,0,0,0} },
  { 0x87B66827201E9F2Bu, 1u, {36,0,0,0}, {27,0,0,0}, {100,0,0,0} },
  { 0x87CB833F7434B7D5u, 2u, {28,1,0,0}, {36,11,0,0}, {100,87,0,0} },
  { 0x889E9D599B7521B2u, 1u, {1,0,0,0}, {18,0,0,0}, {100,0,0,0} },
  { 0x89125D8D958FDB35u, 2u, {11,11,0,0}, {19,27,0,0}, {100,100,0,0} },
  { 0x8BEA6C5AE7D92D10u, 1u, {51,0,0,0}, {43,0,0,0}, {100,0,0,0} },
  { 0x8CF0C78E68C15AE5u, 2u, {10,6,0,0}, {26,21,0,0}, {100,87,0,0} },
  { 0x8F440EBCD8744DE5u, 1u, {51,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0x9082CAC922400F4Bu, 3u, {48,61,62,0}, {40,25,45,0}, {100,87,87,0} },
  { 0x973AA4463054BFC5u, 1u, {28,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0x98C0E882A5DD4854u, 1u, {4,0,0,0}, {6,0,0,0}, {100,0,0,0} },
  { 0x98EFABC143311AFAu, 1u, {6,0,0,0}, {21,0,0,0}, {100,0,0,0} },
  { 0x99B28778049FD43Du, 1u, {6,0,0,0}, {21,0,0,0}, {50,0,0,0} },
  { 0x9CC9BDB7511C9075u, 1u, {51,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0x9D0F69C833C20D3Bu, 2u, {11,21,0,0}, {27,36,0,0}, {100,87,0,0} },
  { 0x9E77A420D943954Du, 2u, {2,6,0,0}, {29,21,0,0}, {100,100,0,0} },
  { 0xA06B78BBE0CB591Bu, 1u, {3,0,0,0}, {10,0,0,0}, {100,0,0,0} },
  { 0xA55CC336BBCD1CEEu, 1u, {62,0,0,0}, {45,0,0,0}, {100,0,0,0} },
  { 0xA5EF1DEA8F37FD43u, 1u, {11,0,0,0}, {27,0,0,0}, {100,0,0,0} },
  { 0xA764AE32E62F9A0Cu, 1u, {62,0,0,0}, {45,0,0,0}, {100,0,0,0} },
  { 0xA807B1BA9C7ACD06u, 2u, {61,62,0,0}, {34,45,0,0}, {100,100,0,0} },
  { 0xA89D7749C59A3C87u, 1u, {2,0,0,0}, {29,0,0,0}, {100,0,0,0} },
  { 0xAE203CB9B4EA2075u, 1u, {10,0,0,0}, {18,0,0,0}, {100,0,0,0} },
  { 0xB0C5E558A34EB5F7u, 2u, {51,61,0,0}, {35,54,0,0}, {100,87,0,0} },
  { 0xB20A270813959219u, 1u, {51,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0xB24D0EA5D770524Bu, 1u, {33,0,0,0}, {24,0,0,0}, {100,0,0,0} },
  { 0xBA12B464EB320CE5u, 1u, {35,0,0,0}, {28,0,0,0}, {100,0,0,0} },
  { 0xBC41A29EB2513FB5u, 1u, {51,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0xBC5D9B0CC943FD53u, 1u, {34,0,0,0}, {27,0,0,0}, {100,0,0,0} },
  { 0xBE3CE65283542B85u, 1u, {51,0,0,0}, {35,0,0,0}, {50,0,0,0} },
  { 0xC3D49839F6B27F43u, 1u, {5,0,0,0}, {12,0,0,0}, {50,0,0,0} },
  { 0xC5B5A4F851FD54D9u, 1u, {51,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0xCCFDE916C9EEC12Cu, 1u, {12,0,0,0}, {28,0,0,0}, {100,0,0,0} },
  { 0xD17F27602E050F80u, 1u, {5,0,0,0}, {19,0,0,0}, {100,0,0,0} },
  { 0xD2E67F32E1F59A98u, 1u, {59,0,0,0}, {35,0,0,0}, {100,0,0,0} },
  { 0xD33B5497916E56F5u, 2u, {10,11,0,0}, {26,27,0,0}, {100,100,0,0} },
  { 0xDC7C6C552D099669u, 1u, {62,0,0,0}, {45,0,0,0}, {100,0,0,0} },
  { 0xDCC0F6C0253B3509u, 4u, {50,50,52,52}, {34,42,36,44}, {100,100,100,100} },
  { 0xE0BC00006BD6F62Du, 1u, {5,0,0,0}, {14,0,0,0}, {100,0,0,0} },
  { 0xE1901EC0B2A043FBu, 1u, {57,0,0,0}, {42,0,0,0}, {50,0,0,0} },
  { 0xE93B1516D75401BAu, 1u, {62,0,0,0}, {45,0,0,0}, {100,0,0,0} },
  { 0xEF1E5E4CA0F78940u, 1u, {12,0,0,0}, {28,0,0,0}, {100,0,0,0} },
};

enum { OPENING_BOOK_ENTRY_COUNT = 87 };

static uint64_t fnv1a64_key(const uint8_t key[34]) {
  uint64_t h = UINT64_C(1469598103934665603);
  unsigned i;
  for (i = 0; i < 34u; i++) {
    h ^= (uint64_t)key[i];
    h *= UINT64_C(1099511628211);
  }
  return h;
}

static uint32_t book_rng_next(uint32_t *state) {
  *state = *state * 1664525u + 1013904223u;
  return *state >> 8;
}

static bool pick_weighted(const opening_book_entry_t *e, uint32_t book_seed,
                        uint8_t *from, uint8_t *to) {
  unsigned i;
  unsigned best = 0;
  if (e->count == 0) {
    return false;
  }
  if (book_seed == 0u) {
    for (i = 1; i < e->count; i++) {
      if (e->weight[i] > e->weight[best]) {
        best = i;
      }
    }
    *from = e->from[best];
    *to = e->to[best];
    return true;
  }
  {
    uint32_t rng = book_seed;
    uint32_t roll;
    uint32_t total = 0;
    for (i = 0; i < e->count; i++) {
      total += (uint32_t)e->weight[i];
    }
    if (total == 0u) {
      return false;
    }
    roll = book_rng_next(&rng) % total;
    for (i = 0; i < e->count; i++) {
      if (roll < (uint32_t)e->weight[i]) {
        *from = e->from[i];
        *to = e->to[i];
        return true;
      }
      roll -= (uint32_t)e->weight[i];
    }
    *from = e->from[e->count - 1u];
    *to = e->to[e->count - 1u];
    return true;
  }
}

static const opening_book_entry_t *find_entry(uint64_t kh) {
  size_t lo = 0;
  size_t hi = OPENING_BOOK_ENTRY_COUNT;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    if (s_book[mid].key < kh) {
      lo = mid + 1;
    } else if (s_book[mid].key > kh) {
      hi = mid;
    } else {
      return &s_book[mid];
    }
  }
  return NULL;
}

bool chess_opening_book_probe(const chess_position *pos, uint32_t book_seed,
                              bool book_enabled, chess_move *out) {
  uint8_t key[34];
  const opening_book_entry_t *e;
  uint8_t from;
  uint8_t to;
  chess_position probe;
  chess_undo undo;
  unsigned last;
  if (!book_enabled || pos == NULL || out == NULL) {
    return false;
  }
  chess_position_key(pos, key);
  e = find_entry(fnv1a64_key(key));
  if (e == NULL) {
    return false;
  }
  if (!pick_weighted(e, book_seed, &from, &to)) {
    return false;
  }
  out->from = from;
  out->to = to;
  out->promotion = CHESS_EMPTY;
  last = (pos->side_to_move == CHESS_WHITE) ? 7u : 0u;
  if (pos->board[from].type == CHESS_PAWN && to / 8u == last) {
    out->promotion = CHESS_QUEEN;
  }
  probe = *pos;
  if (chess_make(&probe, *out, &undo) != CHESS_OK) {
    return false;
  }
  return true;
}

size_t chess_opening_book_position_count(void) {
  return OPENING_BOOK_ENTRY_COUNT;
}

int chess_opening_book_selfcheck(void) {
  return 0;
}
