#!/usr/bin/env python3
"""Generate PeSTO MG/EG PST headers for mcu-max (PST-only, no material)."""
from __future__ import annotations

import ast
import re
import textwrap
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "tools" / "pesto_source.py"
OUT = ROOT / "third_party" / "mcu-max" / "mcumax_pesto_tables.h"

# mcu-max material: pawn engine unit 74 ~= PeSTO centipawn pawn 100.
PESTO_PAWN_CP = 100

PIECE_ORDER = [
    "pawn",
    "knight",
    "bishop",
    "rook",
    "queen",
    "king",
]


def clamp8(v: int) -> int:
    return max(-127, min(127, v))


def scale_pesto(v: int, pawn_unit: int) -> int:
    return clamp8(round(v * pawn_unit / PESTO_PAWN_CP))


def load_tables() -> tuple[dict[str, list[int]], dict[str, list[int]]]:
    text = SRC.read_text()
    mg: dict[str, list[int]] = {}
    eg: dict[str, list[int]] = {}
    for piece in PIECE_ORDER:
        mg_m = re.search(
            rf"mg_{piece}_table\s*=\s*\[(.*?)\]", text, re.S
        )
        eg_m = re.search(
            rf"eg_{piece}_table\s*=\s*\[(.*?)\]", text, re.S
        )
        if not mg_m or not eg_m:
            raise SystemExit(f"missing tables for {piece}")
        mg[piece] = ast.literal_eval("[" + mg_m.group(1) + "]")
        eg[piece] = ast.literal_eval("[" + eg_m.group(1) + "]")
        if len(mg[piece]) != 64 or len(eg[piece]) != 64:
            raise SystemExit(f"bad length for {piece}")
    return mg, eg


def fmt_plane(name: str, values: list[int]) -> str:
    lines = []
    for i in range(0, 64, 8):
        chunk = ", ".join(str(v) for v in values[i : i + 8])
        lines.append(f"    {chunk},")
    body = "\n".join(lines)
    return f"static const int8_t {name}[64] = {{\n{body}\n}};"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--pawn-unit",
        type=int,
        default=74,
        help="mcu-max pawn material units per PeSTO 100cp pawn (default 74)",
    )
    args = ap.parse_args()
    pawn_unit = args.pawn_unit

    mg_raw, eg_raw = load_tables()
    mg_scaled = {
        p: [scale_pesto(v, pawn_unit) for v in mg_raw[p]] for p in PIECE_ORDER
    }
    eg_scaled = {
        p: [scale_pesto(v, pawn_unit) for v in eg_raw[p]] for p in PIECE_ORDER
    }

    chunks = [
        "/* Auto-generated by tools/gen_pesto_pst.py — do not edit. */",
        "/* PeSTO piece-square tables (Ronald Friederich / CPW); PST values only.",
        f"   Scaled int8: round(pesto_cp * {pawn_unit} / {PESTO_PAWN_CP}).",
        "   PeSTO square a1=0 .. h8=63; black uses sq^56 at lookup. */",
        "",
    ]
    for piece in PIECE_ORDER:
        chunks.append(fmt_plane(f"mcumax_pesto_mg_{piece}", mg_scaled[piece]))
        chunks.append(fmt_plane(f"mcumax_pesto_eg_{piece}", eg_scaled[piece]))
        chunks.append("")

    chunks.append(
        "static const int8_t *const mcumax_pesto_mg_planes[6] = {"
    )
    chunks.append(
        "    mcumax_pesto_mg_pawn, mcumax_pesto_mg_knight, mcumax_pesto_mg_bishop,"
    )
    chunks.append(
        "    mcumax_pesto_mg_rook, mcumax_pesto_mg_queen, mcumax_pesto_mg_king,"
    )
    chunks.append("};")
    chunks.append(
        "static const int8_t *const mcumax_pesto_eg_planes[6] = {"
    )
    chunks.append(
        "    mcumax_pesto_eg_pawn, mcumax_pesto_eg_knight, mcumax_pesto_eg_bishop,"
    )
    chunks.append(
        "    mcumax_pesto_eg_rook, mcumax_pesto_eg_queen, mcumax_pesto_eg_king,"
    )
    chunks.append("};")

    OUT.write_text("\n".join(chunks) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
