#!/usr/bin/env python3
"""Generate opening_book.c from opening_lines.txt (host-only; needs python-chess)."""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from collections import defaultdict
from pathlib import Path

try:
    import chess
except ImportError:
    print("python-chess required", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
LINES = ROOT / "components/chess_ai/opening_lines.txt"
OUT_C = ROOT / "components/chess_ai/opening_book.c"
OUT_H = ROOT / "components/chess_ai/opening_book.h"

FNV_OFFSET = 1469598103934665603
FNV_PRIME = 1099511628211


def piece_code(p: chess.Piece | None) -> int:
    if p is None:
        return 0
    base = {chess.PAWN: 1, chess.KNIGHT: 2, chess.BISHOP: 3,
            chess.ROOK: 4, chess.QUEEN: 5, chess.KING: 6}[p.piece_type]
    return base + (6 if p.color == chess.BLACK else 0)


def has_legal_ep_capture(board: chess.Board) -> bool:
    if board.ep_square is None:
        return False
    for mv in board.generate_legal_moves():
        if mv.to_square == board.ep_square and board.piece_at(mv.from_square).piece_type == chess.PAWN:
            return True
    return False


def position_key(board: chess.Board) -> bytes:
    """34-byte key matching chess_position_key() in chess_game.c."""
    key = bytearray(34)
    for i in range(32):
        lo = piece_code(board.piece_at(2 * i))
        hi = piece_code(board.piece_at(2 * i + 1))
        key[i] = (hi << 4) | lo
    castling = 0
    if board.has_kingside_castling_rights(chess.WHITE):
        castling |= 0x01
    if board.has_queenside_castling_rights(chess.WHITE):
        castling |= 0x02
    if board.has_kingside_castling_rights(chess.BLACK):
        castling |= 0x04
    if board.has_queenside_castling_rights(chess.BLACK):
        castling |= 0x08
    key[32] = castling | (0x10 if board.turn == chess.BLACK else 0)
    if has_legal_ep_capture(board):
        key[33] = board.ep_square % 8
    else:
        key[33] = 0xFF
    return bytes(key)


def fnv1a64(data: bytes) -> int:
    h = FNV_OFFSET
    for b in data:
        h ^= b
        h = (h * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
    return h


def uci_to_move(board: chess.Board, uci: str) -> chess.Move:
    mv = chess.Move.from_uci(uci)
    if mv not in board.legal_moves:
        raise ValueError("illegal move %s in %s" % (uci, board.fen()))
    return mv


def core_square(sq: int) -> int:
    """python-chess square index matches core a1=0."""
    return sq


class LineSpec:
    __slots__ = ("weight", "moves", "prefix")

    def __init__(self, weight: int, moves: list[str], prefix: list[str] | None):
        self.weight = weight
        self.moves = moves
        self.prefix = prefix  # opponent-only setup from start (not booked)


def parse_lines(path: Path) -> list[LineSpec]:
    out: list[LineSpec] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if parts[0] == "RESP":
            if len(parts) < 3:
                raise ValueError("RESP needs prefix and moves: %s" % raw)
            prefix = [parts[1]]
            weight = int(parts[2])
            moves = parts[3:]
            if not moves:
                raise ValueError("RESP missing book moves: %s" % raw)
            out.append(LineSpec(weight, moves, prefix))
            continue
        weight = int(parts[0])
        moves = parts[1:]
        if not moves:
            raise ValueError("line missing moves: %s" % raw)
        out.append(LineSpec(weight, moves, None))
    return out


def build_table(lines: list[LineSpec]) -> dict[int, dict[tuple[int, int], int]]:
    """key_hash -> {(from,to): weight}"""
    table: dict[int, dict[tuple[int, int], int]] = defaultdict(dict)
    board = chess.Board()
    for spec in lines:
        board.reset()
        if spec.prefix:
            for uci in spec.prefix:
                board.push(uci_to_move(board, uci))
        for uci in spec.moves:
            k = fnv1a64(position_key(board))
            mv = uci_to_move(board, uci)
            fr = core_square(mv.from_square)
            to = core_square(mv.to_square)
            prev = table[k].get((fr, to), 0)
            table[k][(fr, to)] = max(prev, spec.weight)
            board.push(mv)
    return table


def emit_c(table: dict[int, dict[tuple[int, int], int]]) -> None:
    entries = []
    for kh in sorted(table.keys()):
        moves = table[kh]
        ordered = sorted(moves.items(), key=lambda x: (-x[1], x[0]))
        if len(ordered) > 4:
            raise ValueError("position 0x%x has %d moves (max 4)" % (kh, len(ordered)))
        entries.append((kh, ordered))

    lines: list[str] = []
    lines.append("/* Generated by tools/gen_opening_book.py — do not edit. */")
    lines.append('#include "opening_book.h"')
    lines.append("")
    lines.append("typedef struct {")
    lines.append("  uint64_t key;")
    lines.append("  uint8_t count;")
    lines.append("  uint8_t from[OPENING_BOOK_MAX_ALT];")
    lines.append("  uint8_t to[OPENING_BOOK_MAX_ALT];")
    lines.append("  uint8_t weight[OPENING_BOOK_MAX_ALT];")
    lines.append("} opening_book_entry_t;")
    lines.append("")
    lines.append("static const opening_book_entry_t s_book[] = {")
    for kh, ordered in entries:
        froms = [0, 0, 0, 0]
        tos = [0, 0, 0, 0]
        weights = [0, 0, 0, 0]
        for i, ((fr, to), w) in enumerate(ordered):
            froms[i] = fr
            tos[i] = to
            weights[i] = w
        lines.append(
            "  { 0x%016Xu, %uu, {%u,%u,%u,%u}, {%u,%u,%u,%u}, {%u,%u,%u,%u} },"
            % (kh, len(ordered), *froms, *tos, *weights)
        )
    lines.append("};")
    lines.append("")
    lines.append("enum { OPENING_BOOK_ENTRY_COUNT = %u };" % len(entries))
    lines.append("")
    lines.append("static uint64_t fnv1a64_key(const uint8_t key[34]) {")
    lines.append("  uint64_t h = UINT64_C(1469598103934665603);")
    lines.append("  unsigned i;")
    lines.append("  for (i = 0; i < 34u; i++) {")
    lines.append("    h ^= (uint64_t)key[i];")
    lines.append("    h *= UINT64_C(1099511628211);")
    lines.append("  }")
    lines.append("  return h;")
    lines.append("}")
    lines.append("")
    lines.append("static uint32_t book_rng_next(uint32_t *state) {")
    lines.append("  *state = *state * 1664525u + 1013904223u;")
    lines.append("  return *state >> 8;")
    lines.append("}")
    lines.append("")
    lines.append("static bool pick_weighted(const opening_book_entry_t *e, uint32_t book_seed,")
    lines.append("                        uint8_t *from, uint8_t *to) {")
    lines.append("  unsigned i;")
    lines.append("  unsigned best = 0;")
    lines.append("  if (e->count == 0) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  if (book_seed == 0u) {")
    lines.append("    for (i = 1; i < e->count; i++) {")
    lines.append("      if (e->weight[i] > e->weight[best]) {")
    lines.append("        best = i;")
    lines.append("      }")
    lines.append("    }")
    lines.append("    *from = e->from[best];")
    lines.append("    *to = e->to[best];")
    lines.append("    return true;")
    lines.append("  }")
    lines.append("  {")
    lines.append("    uint32_t rng = book_seed;")
    lines.append("    uint32_t roll;")
    lines.append("    uint32_t total = 0;")
    lines.append("    for (i = 0; i < e->count; i++) {")
    lines.append("      total += (uint32_t)e->weight[i];")
    lines.append("    }")
    lines.append("    if (total == 0u) {")
    lines.append("      return false;")
    lines.append("    }")
    lines.append("    roll = book_rng_next(&rng) % total;")
    lines.append("    for (i = 0; i < e->count; i++) {")
    lines.append("      if (roll < (uint32_t)e->weight[i]) {")
    lines.append("        *from = e->from[i];")
    lines.append("        *to = e->to[i];")
    lines.append("        return true;")
    lines.append("      }")
    lines.append("      roll -= (uint32_t)e->weight[i];")
    lines.append("    }")
    lines.append("    *from = e->from[e->count - 1u];")
    lines.append("    *to = e->to[e->count - 1u];")
    lines.append("    return true;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("static const opening_book_entry_t *find_entry(uint64_t kh) {")
    lines.append("  size_t lo = 0;")
    lines.append("  size_t hi = OPENING_BOOK_ENTRY_COUNT;")
    lines.append("  while (lo < hi) {")
    lines.append("    size_t mid = lo + (hi - lo) / 2;")
    lines.append("    if (s_book[mid].key < kh) {")
    lines.append("      lo = mid + 1;")
    lines.append("    } else if (s_book[mid].key > kh) {")
    lines.append("      hi = mid;")
    lines.append("    } else {")
    lines.append("      return &s_book[mid];")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return NULL;")
    lines.append("}")
    lines.append("")
    lines.append("bool chess_opening_book_probe(const chess_position *pos, uint32_t book_seed,")
    lines.append("                              bool book_enabled, chess_move *out) {")
    lines.append("  uint8_t key[34];")
    lines.append("  const opening_book_entry_t *e;")
    lines.append("  uint8_t from;")
    lines.append("  uint8_t to;")
    lines.append("  chess_position probe;")
    lines.append("  chess_undo undo;")
    lines.append("  unsigned last;")
    lines.append("  if (!book_enabled || pos == NULL || out == NULL) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  chess_position_key(pos, key);")
    lines.append("  e = find_entry(fnv1a64_key(key));")
    lines.append("  if (e == NULL) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  if (!pick_weighted(e, book_seed, &from, &to)) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  out->from = from;")
    lines.append("  out->to = to;")
    lines.append("  out->promotion = CHESS_EMPTY;")
    lines.append("  last = (pos->side_to_move == CHESS_WHITE) ? 7u : 0u;")
    lines.append("  if (pos->board[from].type == CHESS_PAWN && to / 8u == last) {")
    lines.append("    out->promotion = CHESS_QUEEN;")
    lines.append("  }")
    lines.append("  probe = *pos;")
    lines.append("  if (chess_make(&probe, *out, &undo) != CHESS_OK) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  return true;")
    lines.append("}")
    lines.append("")
    lines.append("size_t chess_opening_book_position_count(void) {")
    lines.append("  return OPENING_BOOK_ENTRY_COUNT;")
    lines.append("}")
    lines.append("")
    lines.append("int chess_opening_book_selfcheck(void) {")
    lines.append("  return 0;")
    lines.append("}")

    OUT_C.write_text("\n".join(lines) + "\n", encoding="utf-8")

    h = """/* Position-keyed opening book (adapter layer). Generated table in opening_book.c. */
#ifndef OPENING_BOOK_H
#define OPENING_BOOK_H

#include <stdbool.h>
#include <stddef.h>

#include "chess_core.h"

#define OPENING_BOOK_MAX_ALT 4u

bool chess_opening_book_probe(const chess_position *pos, uint32_t book_seed,
                              bool book_enabled, chess_move *out);

size_t chess_opening_book_position_count(void);

int chess_opening_book_selfcheck(void);

#endif /* OPENING_BOOK_H */
"""
    OUT_H.write_text(h, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lines", type=Path, default=LINES)
    ap.add_argument("--check-keys", action="store_true",
                    help="print SHA256 of sorted key list for tests")
    args = ap.parse_args()
    parsed = parse_lines(args.lines)
    table = build_table(parsed)
    if args.check_keys:
        digest = hashlib.sha256(
            ",".join("%016x" % k for k in sorted(table.keys())).encode()
        ).hexdigest()
        print(digest)
        return 0
    emit_c(table)
    print("Wrote %u positions to %s" % (len(table), OUT_C), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
