#!/usr/bin/env python3
"""Generate opening_book.c from Lichess openings + explorer weight cache."""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

try:
    import chess
except ImportError:
    print("python-chess required", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from opening_book_lib import (  # noqa: E402
    LineSpec,
    RESP_PREFIXES,
    build_position_tree,
    build_table_from_tree,
    emit_lines_txt,
    load_chess_openings_rows,
    load_explorer_cache,
    scale_weights,
    select_opening_lines,
    fen_key,
)

LINES = ROOT / "components/chess_ai/opening_lines.txt"
OUT_C = ROOT / "components/chess_ai/opening_book.c"
OUT_H = ROOT / "components/chess_ai/opening_book.h"
CACHE_PATH = ROOT / "tools/data/opening_explorer_cache.json"

# White first moves allowed at the root (exclude c3 and other junk).
ROOT_WHITE = {"e2e4", "d2d4", "g1f3", "c2c4"}


def emit_c(table: dict[int, dict[tuple[int, int], int]], out_c: Path = OUT_C) -> None:
    entries = []
    for kh in sorted(table.keys()):
        moves = table[kh]
        ordered = sorted(moves.items(), key=lambda x: (-x[1], x[0]))
        if len(ordered) > 4:
            raise ValueError("position 0x%x has %d moves (max 4)" % (kh, len(ordered)))
        entries.append((kh, ordered))

    lines: list[str] = []
    lines.append("/* Generated by tools/gen_opening_book.py — do not edit. */")
    lines.append('#include "opening_book.h"')
    lines.append("")
    lines.append("typedef struct {")
    lines.append("  uint64_t key;")
    lines.append("  uint8_t count;")
    lines.append("  uint8_t from[OPENING_BOOK_MAX_ALT];")
    lines.append("  uint8_t to[OPENING_BOOK_MAX_ALT];")
    lines.append("  uint8_t weight[OPENING_BOOK_MAX_ALT];")
    lines.append("} opening_book_entry_t;")
    lines.append("")
    lines.append("static const opening_book_entry_t s_book[] = {")
    for kh, ordered in entries:
        froms = [0, 0, 0, 0]
        tos = [0, 0, 0, 0]
        weights = [0, 0, 0, 0]
        for i, ((fr, to), w) in enumerate(ordered):
            froms[i] = fr
            tos[i] = to
            weights[i] = w
        lines.append(
            "  { 0x%016Xu, %uu, {%u,%u,%u,%u}, {%u,%u,%u,%u}, {%u,%u,%u,%u} },"
            % (kh, len(ordered), *froms, *tos, *weights)
        )
    lines.append("};")
    lines.append("")
    lines.append("enum { OPENING_BOOK_ENTRY_COUNT = %u };" % len(entries))
    lines.append("")
    lines.append("static uint64_t fnv1a64_key(const uint8_t key[34]) {")
    lines.append("  uint64_t h = UINT64_C(1469598103934665603);")
    lines.append("  unsigned i;")
    lines.append("  for (i = 0; i < 34u; i++) {")
    lines.append("    h ^= (uint64_t)key[i];")
    lines.append("    h *= UINT64_C(1099511628211);")
    lines.append("  }")
    lines.append("  return h;")
    lines.append("}")
    lines.append("")
    lines.append("static uint32_t book_rng_next(uint32_t *state) {")
    lines.append("  *state = *state * 1664525u + 1013904223u;")
    lines.append("  return *state >> 8;")
    lines.append("}")
    lines.append("")
    lines.append("static bool pick_weighted(const opening_book_entry_t *e, uint32_t book_seed,")
    lines.append("                        uint8_t *from, uint8_t *to) {")
    lines.append("  unsigned i;")
    lines.append("  unsigned best = 0;")
    lines.append("  if (e->count == 0) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  if (book_seed == 0u) {")
    lines.append("    for (i = 1; i < e->count; i++) {")
    lines.append("      if (e->weight[i] > e->weight[best]) {")
    lines.append("        best = i;")
    lines.append("      }")
    lines.append("    }")
    lines.append("    *from = e->from[best];")
    lines.append("    *to = e->to[best];")
    lines.append("    return true;")
    lines.append("  }")
    lines.append("  {")
    lines.append("    uint32_t rng = book_seed;")
    lines.append("    uint32_t roll;")
    lines.append("    uint32_t total = 0;")
    lines.append("    for (i = 0; i < e->count; i++) {")
    lines.append("      total += (uint32_t)e->weight[i];")
    lines.append("    }")
    lines.append("    if (total == 0u) {")
    lines.append("      return false;")
    lines.append("    }")
    lines.append("    roll = book_rng_next(&rng) % total;")
    lines.append("    for (i = 0; i < e->count; i++) {")
    lines.append("      if (roll < (uint32_t)e->weight[i]) {")
    lines.append("        *from = e->from[i];")
    lines.append("        *to = e->to[i];")
    lines.append("        return true;")
    lines.append("      }")
    lines.append("      roll -= (uint32_t)e->weight[i];")
    lines.append("    }")
    lines.append("    *from = e->from[e->count - 1u];")
    lines.append("    *to = e->to[e->count - 1u];")
    lines.append("    return true;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("static const opening_book_entry_t *find_entry(uint64_t kh) {")
    lines.append("  size_t lo = 0;")
    lines.append("  size_t hi = OPENING_BOOK_ENTRY_COUNT;")
    lines.append("  while (lo < hi) {")
    lines.append("    size_t mid = lo + (hi - lo) / 2;")
    lines.append("    if (s_book[mid].key < kh) {")
    lines.append("      lo = mid + 1;")
    lines.append("    } else if (s_book[mid].key > kh) {")
    lines.append("      hi = mid;")
    lines.append("    } else {")
    lines.append("      return &s_book[mid];")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return NULL;")
    lines.append("}")
    lines.append("")
    lines.append("bool chess_opening_book_probe(const chess_position *pos, uint32_t book_seed,")
    lines.append("                              bool book_enabled, chess_move *out) {")
    lines.append("  uint8_t key[34];")
    lines.append("  const opening_book_entry_t *e;")
    lines.append("  uint8_t from;")
    lines.append("  uint8_t to;")
    lines.append("  chess_position probe;")
    lines.append("  chess_undo undo;")
    lines.append("  unsigned last;")
    lines.append("  if (!book_enabled || pos == NULL || out == NULL) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  chess_position_key(pos, key);")
    lines.append("  e = find_entry(fnv1a64_key(key));")
    lines.append("  if (e == NULL) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  if (!pick_weighted(e, book_seed, &from, &to)) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  out->from = from;")
    lines.append("  out->to = to;")
    lines.append("  out->promotion = CHESS_EMPTY;")
    lines.append("  last = (pos->side_to_move == CHESS_WHITE) ? 7u : 0u;")
    lines.append("  if (pos->board[from].type == CHESS_PAWN && to / 8u == last) {")
    lines.append("    out->promotion = CHESS_QUEEN;")
    lines.append("  }")
    lines.append("  probe = *pos;")
    lines.append("  if (chess_make(&probe, *out, &undo) != CHESS_OK) {")
    lines.append("    return false;")
    lines.append("  }")
    lines.append("  return true;")
    lines.append("}")
    lines.append("")
    lines.append("size_t chess_opening_book_position_count(void) {")
    lines.append("  return OPENING_BOOK_ENTRY_COUNT;")
    lines.append("}")
    lines.append("")
    lines.append("int chess_opening_book_selfcheck(void) {")
    lines.append("  return 0;")
    lines.append("}")

    out_c.write_text("\n".join(lines) + "\n", encoding="utf-8")

    h = """/* Position-keyed opening book (adapter layer). Generated table in opening_book.c. */
#ifndef OPENING_BOOK_H
#define OPENING_BOOK_H

#include <stdbool.h>
#include <stddef.h>

#include "chess_core.h"

#define OPENING_BOOK_MAX_ALT 4u

bool chess_opening_book_probe(const chess_position *pos, uint32_t book_seed,
                              bool book_enabled, chess_move *out);

size_t chess_opening_book_position_count(void);

int chess_opening_book_selfcheck(void);

#endif /* OPENING_BOOK_H */
"""
    OUT_H.write_text(h, encoding="utf-8")


def add_black_reply_lines(
    cache: dict[str, dict[str, int]],
    line_moves: list[list[str]],
) -> None:
    """One-ply Black replies to common White first moves."""
    setups = [
        (["e2e4"], {"e7e5", "c7c5", "e7e6", "c7c6", "g8f6", "d7d5"}),
        (["d2d4"], {"d7d5", "g8f6", "e7e6", "f7f5", "c7c5"}),
        (["g1f3"], {"d7d5", "g8f6", "c7c5", "e7e6"}),
        (["c2c4"], {"e7e5", "c7c5", "e7e6", "g8f6", "c7c6"}),
    ]
    board = chess.Board()
    for prefix, allowed in setups:
        board.reset()
        for uci in prefix:
            board.push(chess.Move.from_uci(uci))
        fen = fen_key(board)
        counts = cache.get(fen, {})
        picks = scale_weights(counts, allowed)
        for uci in sorted(picks, key=lambda u: (-picks[u], u)):
            seq = prefix + [uci]
            if seq not in line_moves:
                line_moves.append(seq)


def add_resp_continuations(
    cache: dict[str, dict[str, int]],
    specs: list[LineSpec],
) -> None:
    for tag, prefix in RESP_PREFIXES:
        board = chess.Board()
        for uci in prefix:
            board.push(chess.Move.from_uci(uci))
        fen = fen_key(board)
        counts = cache.get(fen, {})
        legal = {m.uci() for m in board.legal_moves}
        if prefix[0] in ("e2e3", "c2c3") and "d7d5" in legal:
            moves = ["d7d5"]
            w = scale_weights(counts, {"d7d5"}).get("d7d5", 80)
        elif prefix[0] == "c2c4":
            allowed = {"e7e5", "g8f6", "c7c5", "e7e6"} & legal
            weighted = scale_weights(counts, allowed)
            top = sorted(weighted.items(), key=lambda x: (-x[1], x[0]))[:2]
            if not top:
                continue
            moves = [uci for uci, _w in top]
            w = top[0][1]
        else:
            weighted = scale_weights(counts, legal)
            top = sorted(weighted.items(), key=lambda x: (-x[1], x[0]))[:2]
            if not top:
                continue
            moves = [uci for uci, _w in top]
            w = top[0][1]
        specs.append(
            LineSpec(w, moves, prefix, "RESP/%s lichess weights" % tag)
        )


def trim_root_white(tree: dict[str, set[str]], cache: dict[str, dict[str, int]]) -> None:
    board = chess.Board()
    fen = fen_key(board)
    children = tree.get(fen, set())
    filtered = {m for m in children if m in ROOT_WHITE}
    if filtered:
        tree[fen] = filtered
    counts = cache.get(fen, {})
    tree[fen] = set(scale_weights(counts, tree[fen]).keys())


def collect_line_moves(rows_meta: list[tuple[str, str, list[str]]]) -> list[list[str]]:
    return [moves for _e, _n, moves in rows_meta]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lines", type=Path, default=LINES)
    ap.add_argument("--cache", type=Path, default=CACHE_PATH)
    ap.add_argument("--check-keys", action="store_true",
                    help="print SHA256 of sorted key list for tests")
    ap.add_argument("--out-c", type=Path, default=OUT_C,
                    help="output opening_book.c path (default: shipped file)")
    args = ap.parse_args()

    if not args.cache.is_file():
        print("Missing cache %s — run tools/fetch_opening_explorer_cache.py" % args.cache,
              file=sys.stderr)
        return 1

    cache, cache_meta = load_explorer_cache(args.cache)
    rows = load_chess_openings_rows()
    picked = select_opening_lines(rows)
    if len(picked) < 20:
        print("Too few opening lines selected (%d)" % len(picked), file=sys.stderr)
        return 1

    line_moves = collect_line_moves(picked)
    add_black_reply_lines(cache, line_moves)

    specs: list[LineSpec] = []
    for eco, name, moves in picked:
        specs.append(LineSpec(100, moves, None, "%s %s" % (eco, name)))
    add_resp_continuations(cache, specs)

    prefixes = [p for _t, p in RESP_PREFIXES]
    tree = build_position_tree(line_moves, prefixes)
    trim_root_white(tree, cache)

    # Merge RESP book moves into tree.
    for spec in specs:
        if not spec.prefix:
            continue
        board = chess.Board()
        for uci in spec.prefix:
            board.push(chess.Move.from_uci(uci))
        node_fen = fen_key(board)
        for uci in spec.moves:
            tree[node_fen].add(uci)

    table = build_table_from_tree(tree, cache)

    if args.check_keys:
        digest = hashlib.sha256(
            ",".join("%016x" % k for k in sorted(table.keys())).encode()
        ).hexdigest()
        print(digest)
        return 0

    try:
        cache_path_meta = str(args.cache.relative_to(ROOT))
    except ValueError:
        cache_path_meta = str(args.cache)
    emit_lines_txt(
        args.lines,
        specs,
        {
            "cache_path": cache_path_meta,
            "primary_source": cache_meta.get("primary_source"),
            "snapshot_date": cache_meta.get("snapshot_date"),
        },
    )
    emit_c(table, args.out_c)
    print("Wrote %u positions to %s" % (len(table), args.out_c), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
